language: php
sudo: false
php:
 - 7.3
 - nightly
before_script: composer install
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8229d26a4f90bcc6cd67
script: vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests
